name: UI Automation test pipeline
on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: On Which environment you would like to run tests.
        type: choice
        required: true
        options:
           - dev
           - demo
           - prod
        default: dev
        
      BROWSER:
        description: On Which browser you would like to run tests. (By default headless chrome would run).
         Right now only added support for chrome, but we can add all other browsers as we continue.
        type: choice
        required: false
        options:
           - CHROME
           - FIREFOX
           - SAFARI
           - HEADLESS_CHROME
           - CHROME_BROWSERSTACK
        default: HEADLESS_CHROME
        
      REMOTE_NODE_URL:
         description: Please enter the selenium grid URL in case you want to run tests there.
          Or you can enter CHROME_BROWSERSTACK for browstack cloud run.
         type: string
         required: false

         
env:
  ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
  BROWSER: ${{ inputs.BROWSER }}
  REMOTE_NODE_URL: ${{ inputs.REMOTE_NODE_URL }}


jobs:
  Build:
    runs-on: ubuntu-latest   
    name: Build and Run tests

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Install Google Chrome # Using shell script to install Google Chrome
      run: |
       chmod +x ./scripts/InstallChrome.sh
        ./scripts/InstallChrome.sh
        
    - name: Run UI TestSuite
      env: # lookup key as an environment variable
         BROWSERSTACK_URL: ${{ secrets.BROWSERSTACK_URL }}
         EVRA_PASSWORD: ${{ secrets.EVRA_PASSWORD }}
      run: mvn clean install -f pom.xml
         
    - name: Save allure test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
          name: allure-results
          path: |
            allure-results
  
  Publish:
    if: ${{ always()}}
    needs: Build
    name: Publish Allure Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
         allure_results: build/allure-results
         gh_pages: gh-pages
         allure_report: allure-report
         allure_history: allure-history
         keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
          
