name: Deploy platform to demo environment
on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: On Which environment you would like to run tests.
        type: string
        required: true
        options:
           - dev
           - demo
           - prod
        default: dev
        
      BROWSER:
        description: On Which browser you would like to run tests. (By default headless chrome would run).
         Right now only added support for chrome, but we can add all other browsers as we continue.
        type: string
        required: false
        options:
           - CHROME
           - FIREFOX
           - SAFARI
           - HEADLESS_CHROME
           - CHROME_BROWSERSTACK
        default: HEADLESS_CHROME
        
      REMOTE_NODE_URL:
         description: Please enter the selenium grid URL in case you want to run tests there.
          Or you can choose BROWSERSTACK which is also supported.
         type: string
         required: false
         options:
            - BROWSERSTACK

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Run UI tests
      env: # lookup key as an environment variable
        BROWSERSTACK_URL: ${{ secrets.BROWSERSTACK_URL }}
      run: mvn clean install -f pom.xml
    - name: Save test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
          name: allure-results
          path: |
            allure-results
