name: UI Automation test pipeline
on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: On Which environment you would like to run tests.
        type: choice
        required: true
        options:
           - dev
           - demo
           - prod
        default: dev
        
      BROWSER:
        description: On Which browser you would like to run tests. (By default headless chrome would run).
         Right now only added support for chrome, but we can add all other browsers as we continue.
        type: choice
        required: false
        options:
           - CHROME
           - FIREFOX
           - SAFARI
           - HEADLESS_CHROME
           - CHROME_BROWSERSTACK
        default: HEADLESS_CHROME
        
      REMOTE_NODE_URL:
         description: Please enter the selenium grid URL in case you want to run tests there.
          Or you can enter CHROME_BROWSERSTACK for browstack cloud run.
         type: string
         required: false

         
env:
  ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
  BROWSER: ${{ inputs.BROWSER }}
  REMOTE_NODE_URL: ${{ inputs.REMOTE_NODE_URL }}


jobs:
  build:

    runs-on: ubuntu-latest   

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - uses: nanasess/setup-chromedriver@v1
    - name: Install chromedriver
      with:
         # Optional: do not specify to match Chrome's version
           chromedriver-version: '88.0.4324.96'
    - run: |
       export DISPLAY=:99
       chromedriver --url-base=/wd/hub &
       sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

    - name: Run UI tests
      env: # lookup key as an environment variable
        BROWSERSTACK_URL: ${{ secrets.BROWSERSTACK_URL }}
        EVRA_PASSWORD: ${{ secrets.EVRA_PASSWORD }}
      run: mvn clean install -f pom.xml
    - name: Save test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
          name: allure-results
          path: |
            allure-results
